const productTypes = {
  CREATE_NEW_PRODUCT: 'CREATE_NEW_PRODUCT',
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  FETCH_PRODUCT: 'FETCH_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  EDIT_PRODUCT: 'EDIT_PRODUCT'

};

export default productTypes;